### ISSUE TITLE
请问 Java 序列化后的对象详细结构图是如何生成的？

### ISSUE THREAD

**Issue by XhstormR** [Cryin/Paper#1]
序列化后的SerialObject对象详细结构：
```
STREAM_MAGIC (2 bytes) 0xACED 
STREAM_VERSION (2 bytes) 0x0005
    TC_OBJECT (1 byte) 0x73
        TC_CLASSDESC (1 byte) 0x72
        className
            length (2 bytes) 0x24 = 36
            text (36 bytes) com.xxxxxx.sec.web.home.SerialObject
        serialVersionUID (8 bytes) 0x4FDAAF97F8CCC5E1 = 5754104541168322017
        classDescInfo
            classDescFlags (1 byte) 0x02 = SC_SERIALIZABLE
            fields
                count (2 bytes) 2
                field[0]
                    primitiveDesc
                        prim_typecode (1 byte) I = integer
                        fieldName
                            length (2 bytes) 2
                            text (2 bytes) id
                field[1]
                    objectDesc
                        obj_typecode (1 byte) L = object
                        fieldName
                            length (2 bytes) 4
                            text (4 bytes)  name
                        className1
                            TC_STRING (1 byte) 0x74
                                length (2 bytes) 0x12 = 18
                                text (18 bytes) Ljava/lang/String;
 
            classAnnotation
                TC_ENDBLOCKDATA (1 byte) 0x78
 
            superClassDesc
                TC_NULL (1 byte) 0x70
    classdata[]
        classdata[0] (4 bytes) 0xe107 = id = 2017
        classdata[1]
            TC_STRING (1 byte) 0x74
            length (2 bytes) 5
            text (8 bytes) cryin
```
看着像是程序解析生成的，请问是哪款工具啊？

来源：https://github.com/Cryin/Paper/blob/master/%E5%BA%94%E7%94%A8%E5%AE%89%E5%85%A8:JAVA%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96%E6%BC%8F%E6%B4%9E%E4%B9%8B%E6%AE%87.md

**Comment by Cryin** [comment]
单步调试看出来的，没啥工具------------------ 原始邮件 ------------------
发件人: "XhstormR"<notifications@github.com>
发送时间: 2020年4月22日(星期三) 下午5:42
收件人: "Cryin/Paper"<Paper@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Cryin/Paper] 请问 Java 序列化后的对象详细结构图是如何生成的？ (#1)




 
序列化后的SerialObject对象详细结构：
 STREAM_MAGIC (2 bytes) 0xACED  STREAM_VERSION (2 bytes) 0x0005     TC_OBJECT (1 byte) 0x73         TC_CLASSDESC (1 byte) 0x72         className             length (2 bytes) 0x24 = 36             text (36 bytes) com.xxxxxx.sec.web.home.SerialObject         serialVersionUID (8 bytes) 0x4FDAAF97F8CCC5E1 = 5754104541168322017         classDescInfo             classDescFlags (1 byte) 0x02 = SC_SERIALIZABLE             fields                 count (2 bytes) 2                 field[0]                     primitiveDesc                         prim_typecode (1 byte) I = integer                         fieldName                             length (2 bytes) 2                             text (2 bytes) id                 field[1]                     objectDesc                         obj_typecode (1 byte) L = object                         fieldName                             length (2 bytes) 4                             text (4 bytes)  name                         className1                             TC_STRING (1 byte) 0x74                                 length (2 bytes) 0x12 = 18                                 text (18 bytes) Ljava/lang/String;               classAnnotation                 TC_ENDBLOCKDATA (1 byte) 0x78               superClassDesc                 TC_NULL (1 byte) 0x70     classdata[]         classdata[0] (4 bytes) 0xe107 = id = 2017         classdata[1]             TC_STRING (1 byte) 0x74             length (2 bytes) 5             text (8 bytes) cryin  
看着像是程序解析生成的，请问是哪款工具啊？
 
来源：https://github.com/Cryin/Paper/blob/master/%E5%BA%94%E7%94%A8%E5%AE%89%E5%85%A8:JAVA%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96%E6%BC%8F%E6%B4%9E%E4%B9%8B%E6%AE%87.md
 
&mdash;

**Comment by XhstormR** [comment]
强，竟如此工整。
